name: "Implementation Task"
description: "Describe what needs to be implemented."
title: "[Implementation]: "
labels: [enhancement]
body:
  - type: textarea
    id: what_will_be_implemented
    attributes:
      label: "What will be implemented"
      description: "Describe the feature or functionality to be implemented."
      placeholder: "Enter details about what needs to be done."
    validations:
      required: true
  - type: dropdown
    id: state_of_implementation
    attributes:
      label: "State of implementation"
      options:
        - Not started
        - In progress
        - Completed
    validations:
      required: true
  - type: textarea
    id: associated_bugs
    attributes:
      label: "Associated bugs"
      description: "List any bugs related to this implementation."
      placeholder: "Enter bug references or issue numbers if applicable."
